<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: Problem-solving | That TDD Fellow | Tech Blog | Screencasts]]></title>
  <link href="http://www.tddfellow.com/blog/categories/problem-solving/atom.xml" rel="self"/>
  <link href="http://www.tddfellow.com/"/>
  <updated>2019-05-22T22:49:26+02:00</updated>
  <id>http://www.tddfellow.com/</id>
  <author>
    <name><![CDATA[Oleksii Fedorov (waterlink)]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Getting Stuck While Doing TDD. Part 3: Triangulation to the Rescue!]]></title>
    <link href="http://www.tddfellow.com/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue/"/>
    <updated>2016-08-31T02:35:32+02:00</updated>
    <id>http://www.tddfellow.com/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue</id>
    <content type="html"><![CDATA[<p>Welcome back to the &ldquo;Getting Stuck While Doing TDD&rdquo; series. Today we are going to learn the Golden Rule of TDD and how to not get stuck while doing TDD.</p>

<h2>TL;DR</h2>

<ul>
<li>&ldquo;As tests get more specific, production code gets more generic&rdquo;.</li>
<li><code>RED</code> is as important as other in Red-Green-Refactor cycle. If next test does not fail, it is either: already implemented, or has to wait until a later time (until it will fail).</li>
<li><p>At its core the Triangulation Technique has the following idea:</p>

<p>After implementing one business rule (with Red-Green-Refactor) make sure to find all &ldquo;weirdnesses&rdquo; or non-generalities in the production code and one-by-one eliminate them by writing a test, that proves such non-generality, and then making it pass while removing non-generality. This is the third cycle of TDD - Mini Cycle.</p></li>
</ul>


<!--more-->


<p>This is a series of articles:</p>

<ol>
<li><a href="/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example/">Part 1: Example</a></li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through/">Part 2: Buggy Code and Forcing Our Way Through</a></li>
<li>Part 3: Triangulation to the Rescue! (reading this)</li>
</ol>


<p>Shall we get started?</p>

<h2>Specific/Generic Rule of TDD</h2>

<blockquote><p>As tests get more specific, production code gets more generic.</p></blockquote>

<p>When making the next failing test pass, our production code should also pass a whole class of similar tests. Best shown in the very simple example. The task at hand is to write the function <code>sum(a, b)</code> that will add two numbers. Let&rsquo;s see us a violation of the Specific/Generic rule:</p>

<pre><code class="ruby">expect(sum(2, 2)).to eq(4)
# =&gt; NoMethodError: undefined method `sum'

def sum(a, b); end
# =&gt; expected: 4, got: nil

def sum(a, b)
  4
end
# =&gt; PASS

expect(sum(2, 3)).to eq(5)
# =&gt; expected: 5, got: 4

def sum(a, b)
  if b == 2
    4
  else
    5
  end
end
# =&gt; PASS
</code></pre>

<p>The production code to make this last test pass is as specific as the failing test now. The test of the same class (where we change the value of the <code>b</code> parameter) will fail for it:</p>

<pre><code class="ruby">expect(sum(2, 42)).to eq(44)
# =&gt; expected: 44, got: 5
</code></pre>

<p>To follow the Specific/Generic rule we ought to make <code>4</code> into <code>2 + b</code> like that:</p>

<pre><code class="ruby">def sum(a, b)
  2 + b
end
# =&gt; PASS
</code></pre>

<p>This way, when we change <code>b</code> to any value it will still pass the test, aside from the fact, that we didn&rsquo;t do anything about <code>a</code>. This is because we still don&rsquo;t have any test showing us, that parameter <code>a</code> is important, like the following one:</p>

<pre><code class="ruby">expect(sum(4, 7)).to eq(11)
# =&gt; expected: 11, got: 9
</code></pre>

<p>Again we can make it pass in a very specific fashion by introducing specific <code>if</code> statement, or we could do it to pass the whole class of such tests:</p>

<pre><code class="ruby">def sum(a, b)
  a + b
end
# =&gt; PASS
</code></pre>

<p>Have you noticed, that from the test suite side we had to &ldquo;prove&rdquo; that some knowledge in the system is important and had to be used? This technique is called Triangulation.</p>

<p><div class="v2-subscribe--inline">
  




  


<div class="mc_embed_signup">
  <form action="//tddfellow.us14.list-manage.com/subscribe/post?u=535a10a8c0274c9a7ebac4f34&amp;id=7f9f94015a" method="post" class="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div class="mc_embed_signup_scroll">
      <h3>Want more articles like this delivered to your inbox?</h3>
      <div class="mc-field-group">
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_535a10a8c0274c9a7ebac4f34_7f9f94015a" tabindex="-1" value=""></div>
        <input type="email" value="" name="EMAIL" class="required email mce-EMAIL" placeholder="Enter your email">
        <input type="submit" value="Subscribe" name="subscribe" class="button mc-embedded-subscribe">
      </div>
      <div class="">
        <em>(we respect your privacy, unsubscribe at any time)</em>
      </div>
    </div>
  </form>
</div>


</div>
</p>

<h2>Triangulation Technique</h2>

<p>In the essence, Triangulation technique has a very simple idea at its core:</p>

<ol>
<li>Change certain important* knowledge in the system.</li>
<li>Assert that the production code behaves in an accordingly expected manner.</li>
</ol>


<p><em>* - important from the perspective of the system or unit under the test</em></p>

<h2>Red-Green-Refactor has to have all stages</h2>

<p>One Red-Green-Refactor cycle really has to have all stages in it. And I&rsquo;m not ranting right now about &ldquo;Refactor&rdquo; stage, that is a given. Rather, I insist on the &ldquo;Red&rdquo; stage - in TDD, when we write a new test, it has to fail. Writing tests that do not fail is another way to get ourselves stuck while doing TDD. One could ask: &ldquo;If I can&rsquo;t write this test because it does not fail, what should I do about the requirement it represents?&rdquo;, and the answer is rather simple - either this requirement is already implemented and tested by other tests, or we still need this test and we will get back to it later when it actually will fail.</p>

<p>As we can remember, in the first part of these series, we were going through an <code>OrderKindValidator</code> example, and we were writing multiple tests in a row, that were all expecting the same outcome and of course they didn&rsquo;t fail, because we had one line in our function that made them all pass. If we were to sprinkle some other tests, that do fail (like a test for a valid order kind), after making it pass, all of these tests will now be failing and therefore they are good candidates for our next test. Let&rsquo;s see it with our own eyes:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be empty")
  .when_order_kind_is_absent
# =&gt; expected InvalidOrderError with "Order kind can not be empty",
# =&gt; got #&lt;NoMethodError:
# =&gt;      undefined method `validate' for #&lt;OrderKindValidator:0x000000020335c0&gt;&gt;

class OrderKindValidator
  def validate(order)
  end
end
# =&gt; expected InvalidOrderError with "Order kind can not be empty"
# =&gt; but nothing was raised

def validate(order)
  raise InvalidOrderError, "Order kind can not be empty"
end
# =&gt; PASS
</code></pre>

<p>Now is the point, where we have to choose our next test, and last time we have chosen the test with the same outcome and it did not go so well. Let&rsquo;s choose a test with different outcome, e.g.: when valid order kind is provided:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(private))
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can not be empty&gt;
</code></pre>

<p>Now, we have 2 options, to either check for <code>order[:kind] == %w(private)</code> or to check for <code>order[:kind]</code> being absent. It does not matter what we choose at this point, so let&rsquo;s go with the first one:</p>

<pre><code class="ruby">def validate(order)
  if order[:kind] == %w(private)
    return
  end

  raise InvalidOrderError, "Order kind can not be empty"
end
# =&gt; PASS
</code></pre>

<p>Now let&rsquo;s apply Triangulation technique. We should always ask ourselves the question: &ldquo;What is weird about this code?&rdquo; and &ldquo;What failing test should I write to point out this weirdness?&rdquo;. First weirdness we can spot is that the validator currently accepts only one order kind - <code>private</code>. According to our requirements it should also accept <code>corporate</code>:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(corporate))
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can not be empty&gt;

def validate(order)
  kinds = order[:kind]
  if kinds == %w(private) || kinds == %w(corporate)
    # ...
end
# =&gt; PASS
</code></pre>

<p>We also know, that our system should handle duplicate entries in <code>order[:kind]</code>:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(private private))
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can not be empty&gt;

def validate(order)
  kinds = order[:kind]
  if kinds.include?("private") || kinds == %w(corporate)
    # ...
end
# =&gt; expected InvalidOrderError with "Order kind can not be empty",
# =&gt; got #&lt;NoMethodError: undefined method `include?'
# =&gt; for nil:NilClass&gt;
</code></pre>

<p>Wow! We, of course, can check for <code>kinds</code> to not be <code>nil</code>, but I would rather listen to this test failure and put a check for <code>kinds</code> being absent (and this makes for our second check, that we could have chosen from):</p>

<pre><code class="ruby">def validate(order)
  kinds = order[:kind]

  if kinds.nil?
    raise InvalidOrderError, "Order kind can not be empty"
  end

  if kinds.include?("private") || kinds == %w(corporate)
    return
  end

  raise InvalidOrderError, "Order kind can not be empty"
end
# =&gt; PASS
</code></pre>

<p>So this passes all our tests. It may look weird, and this is exactly the pointer for us which test to write next to prove, that this weirdness is incorrect:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
  .when_order_kind_is(%w(invalid))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can be one of: 'private', 'corporate', 'bundle'",
# =&gt; got #&lt;InvalidOrderError: Order kind can not be empty&gt;

def validate(order)
  # ...

  raise InvalidOrderError,
    "Order kind can be one of: 'private', 'corporate', 'bundle'"
end
# =&gt; PASS
</code></pre>

<p>Production code starts looking not so clean and I think it is time to give things proper names:</p>

<pre><code class="ruby">class OrderKindValidator
  def validate(order)
    kinds = order[:kind]

    if empty?(kinds)
      fail_with("Order kind can not be empty")
    end

    unless valid?(kinds)
      fail_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    end
  end

  def valid?(kinds)
    kinds.include?("private") || kinds == %w(corporate)
  end

  def empty?(kinds)
    kinds.nil?
  end

  def fail_with(message)
    raise InvalidOrderError, message
  end
end
</code></pre>

<p>There is only one weirdness, that is left for triangulation in current production code, before we can move on to the next requirement - <code>private</code> can be duplicated while <code>corporate</code> can not:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(corporate corporate))
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;

def valid?(kinds)
  kinds.include?("private") ||
      kinds.include?("corporate")
end
# =&gt; PASS
</code></pre>

<p>Great, now we can safely go back to our empty order kind edge cases:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be empty")
  .when_order_kind_is([])
# =&gt; expected InvalidOrderError with "Order kind can not be empty",
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;

def empty?(kinds)
  kinds.nil? ||
      kinds.empty?
end
# =&gt; PASS

it_fails_with("Order kind can not be empty")
  .when_order_kind_is([nil])
# =&gt; expected InvalidOrderError with "Order kind can not be empty",
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;

def empty?(kinds)
  kinds.nil? ||
      kinds.empty? ||
      kinds[0].nil?
end
# =&gt; PASS

it_fails_with("Order kind can not be empty")
  .when_order_kind_is([""])
# =&gt; expected InvalidOrderError with "Order kind can not be empty",
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;

def empty?(kinds)
  kinds.nil? ||
      kinds.empty? ||
      kinds[0].nil? ||
      kinds[0].empty?
end
# =&gt; PASS
</code></pre>

<p>And it is a good opportunity to eliminate some duplication:</p>

<pre><code class="ruby">def empty?(kinds)
  empty_value?(kinds) ||
      empty_value?(kinds[0])
end

def empty_value?(value)
  value.nil? || value.empty?
end
</code></pre>

<p>Now, it is a good time to triangulate, because we have a weirdness in our code: <code>kinds[0]</code>. To prove that this is too specific we can write another test:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be empty")
  .when_order_kind_is(["private", ""])
# =&gt; expected InvalidOrderError with "Order kind can not be empty"
# =&gt; but nothing was raised

def empty?(kinds)
  empty_value?(kinds) ||
      kinds.any? { |kind| empty_value?(kind) }
end
# =&gt; PASS
</code></pre>

<p>Notice, how every single test that we have written was failing and how easy it was to make it pass. This suggests that we are probably moving in the right direction. Let&rsquo;s test our next requirement - we can combine <code>private</code> and <code>bundle</code>:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(private bundle))
# =&gt; PASS
</code></pre>

<p>Wait a minute. This is really bad. We should have a failing test here. This happened because we are checking only for the inclusion of <code>private</code> or <code>corporate</code> and we do not care about anything else in the <code>order[:kind]</code> array. We have to discard this test and try to go with failing version of the same business rule - invalid order kind can not be combined with <code>private</code>:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
  .when_order_kind_is(%w(private invalid))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can be one of: 'private', 'corporate', 'bundle'"
# =&gt; but nothing was raised

def valid?(kinds)
  return false if kinds[1] == "invalid"

  kinds.include?("private") ||
      kinds.include?("corporate")
end
# =&gt; PASS
</code></pre>

<p>While this works, it leads to two other weirdnesses: <code>kinds[1]</code> and <code>"invalid"</code>, let&rsquo;s the latter first:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
  .when_order_kind_is(%w(private another_invalid))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can be one of: 'private', 'corporate', 'bundle'"
# =&gt; but nothing was raised

def valid?(kinds)
  return false if kinds[1] &amp;&amp; kinds[1] != "private"

  kinds.include?("private") ||
      kinds.include?("corporate")
end
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;
# .. and more failures ..
</code></pre>

<p>Other tests fail now, from them it is possible to see, that second kind should be either <code>private</code> or <code>corporate</code>:</p>

<pre><code class="ruby">def valid?(kinds)
  return false if kinds[1] &amp;&amp;
      kinds[1] != "private" &amp;&amp;
      kinds[1] != "corporate"

  kinds.include?("private") ||
      kinds.include?("corporate")
end
# =&gt; PASS
</code></pre>

<p>This looks rather clunky, we should make it a bit cleaner:</p>

<pre><code class="ruby">ALLOWED_ORDER_KINDS = %w(private corporate)

def valid?(kinds)
  return false if kinds[1] &amp;&amp;
      !ALLOWED_ORDER_KINDS.include?(kinds[1])

  kinds.include?("private") ||
      kinds.include?("corporate")
end
</code></pre>

<p>Let&rsquo;s eliminate the other weirdness - <code>kinds[1]</code>, it probably should verify all kinds in the array:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
  .when_order_kind_is(%w(invalid private))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can be one of: 'private', 'corporate', 'bundle'"
# =&gt; but nothing was raised

def valid?(kinds)
  return false if kinds.any? { |kind|
    !ALLOWED_ORDER_KINDS.include?(kind)
  }

  kinds.include?("private") ||
      kinds.include?("corporate")
end
# =&gt; PASS
</code></pre>

<p>And now this can be greatly simplified by inverting the boolean logic:</p>

<pre><code class="ruby">def valid?(kinds)
  kinds.all? { |kind|
    ALLOWED_ORDER_KINDS.include?(kind)
  }
end
</code></pre>

<p>Now that we have dealt with all weirdnesses in our production code, let&rsquo;s get back to our requirement:</p>

<pre><code class="ruby">it_does_not_fail
  .when_order_kind_is(%w(private bundle))
# =&gt; expected no Exception,
# =&gt; got #&lt;InvalidOrderError: Order kind can be one of: 'private', 'corporate', 'bundle'&gt;
</code></pre>

<p>Wow! Now it fails exactly as it should. This means that it is now the right time for this test! Let&rsquo;s make it pass by adding <code>bundle</code> to the list of allowed order kinds:</p>

<pre><code class="ruby">ALLOWED_ORDER_KINDS = %w(private corporate bundle)
# =&gt; PASS
</code></pre>

<p>Nice! Our next requirement is about <code>bundle</code> not being used on its own, i.e.: either <code>private</code> or <code>corporate</code> is required:</p>

<pre><code class="ruby">it_fails_with("Order kind should be 'private' or 'corporate'")
  .when_order_kind_is(%w(bundle))
# =&gt; expected InvalidOrderError with "Order kind should be 'private' or 'corporate'"
# =&gt; but nothing was raised

def validate(order)
  # ...

  if kinds == %w(bundle)
    fail_with("Order kind should be 'private' or 'corporate'")
  end
end
# =&gt; PASS
</code></pre>

<p>And this is good enough, because that is really the only case, when this can happen until the list of allowed order kinds is extended by future business requirements. We should at least give this condition a proper name:</p>

<pre><code class="ruby">unless has_required?(kinds)
  fail_with("Order kind should be 'private' or 'corporate'")
end

# ...

def has_required?(kinds)
  kinds != %w(bundle)
end
</code></pre>

<p>Except, that we could provide duplicated <code>bundle</code>:</p>

<pre><code class="ruby">it_fails_with("Order kind should be 'private' or 'corporate'")
  .when_order_kind_is(%w(bundle bundle))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind should be 'private' or 'corporate'"
# =&gt; but nothing was raised

def has_required?(kinds)
  # Easy to fix if we de-duplicate it with #uniq:
  kinds.uniq != %w(bundle)
end
# =&gt; PASS
</code></pre>

<p>Now it is time to move on to the final requirement about conflicts between <code>private</code> and <code>corporate</code>:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be 'private' and 'corporate' at the same time")
  .when_order_kind_is(%w(private corporate))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can not be 'private' and 'corporate' at the same time"
# =&gt; but nothing was raised

def validate(order)
  # ...

  if kinds == %w(private corporate)
    fail_with("Order kind can not be 'private' and 'corporate' at the same time")
  end
end
# =&gt; PASS
</code></pre>

<p>Of course, <code>kinds == %w(private corporate)</code> can be considered too specific for production code, we should triangulate it:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be 'private' and 'corporate' at the same time")
  .when_order_kind_is(%w(corporate private))
# =&gt; expected InvalidOrderError
# =&gt; with "Order kind can not be 'private' and 'corporate' at the same time"
# =&gt; but nothing was raised

if kinds.include?("private") &amp;&amp;
    kinds.include?("corporate")
  fail_with("Order kind can not be 'private' and 'corporate' at the same time")
end
# =&gt; PASS
</code></pre>

<p>And, finally, let&rsquo;s give this condition a proper name:</p>

<pre><code class="ruby">if has_conflicts?(kinds)
  fail_with("Order kind can not be 'private' and 'corporate' at the same time")
end

# ...

def has_conflicts?(kinds)
  kinds.include?("private") &amp;&amp;
    kinds.include?("corporate")
end
</code></pre>

<p>I believe we are done now. Source for this example can be found in <a href="https://github.com/waterlink/order_kind_validator/pull/3">an open pull request here</a>.</p>

<p>Let&rsquo;s recap how Triangulation technique worked for us here.</p>

<h2>Triangulation Technique in Depth</h2>

<p>The main goal of triangulation is to prove that the code is not general enough along some axis (class of tests) by writing a test and then making sure it passes. Effective application of the technique requires to prove and eliminate all such &ldquo;weirdnesses&rdquo; or non-generalities from the production code after each Red-Green-Refactor cycle for business requirements. This is, in fact, the 3rd cycle of Test-Driven-Development called Mini Cycle of TDD, it should be executed about every 10 minutes.</p>

<p>Another observation is that following this technique we are introducing only one small piece of knowledge into our production code, for example:</p>

<ul>
<li>When writing a test for next business requirement, we are introducing the fact that we need an <code>if</code> statement with a certain body (in this example it was a <code>raise error</code> statement). Since we can not introduce the <code>if</code> statement without a condition we need to put some condition there and we put a very specific condition on purpose since we know that it is tested and it is simple.</li>
<li>Next, we are proving that this condition is too specific by writing a test, and then making it pass with a more generic solution. This way we are introducing a tiny little bit more knowledge in our production code.</li>
<li>We are repeating this iterative process until the production code is generic enough for the current specification (test suite). And we start over. This is the Mini Cycle of TDD.</li>
</ul>


<h2>Bottom Line</h2>

<p>Today we have learned the Golden Rule of TDD - &ldquo;As tests get more specific, production code gets more generic&rdquo;, and we have learned the Triangulation Technique, that allows us to follow this rule in an incremental and confident way. Additionally, we have learned, that following Red-Green-Refactor strictly is important, and this includes even the <code>RED</code> stage of this cycle - when the test for business requirement does not fail, it is either: already implemented or it has to wait for later.</p>

<p>This is a series of articles:</p>

<ol>
<li><a href="/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example/">Part 1: Example</a></li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through/">Part 2: Buggy Code and Forcing Our Way Through</a></li>
<li>Part 3: Triangulation to the Rescue! (reading this)</li>
</ol>


<p>You would not want to miss next articles on this tech blog, we still have a lot to talk about:</p>

<ul>
<li>Continuous Integration and Continuous Delivery - importance of not impeding others,</li>
<li>Open-Closed Principle - changing behavior by adding new code,</li>
<li>Mutational Testing, &ldquo;Build Your Own Testing Framework&rdquo; series, 4 Cycles of TDD, Test-Driven Development screencasts and so much more!</li>
</ul>


<h2>Thanks!</h2>

<p>Thank you for reading, my dear reader. If you liked it, please share this article on social networks and follow me on twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>

<p>If you have any questions or feedback for me, don&rsquo;t hesitate to reach me out on Twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Getting Stuck While Doing TDD. Part 2: Buggy Code and Forcing Our Way Through]]></title>
    <link href="http://www.tddfellow.com/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through/"/>
    <updated>2016-08-31T02:35:06+02:00</updated>
    <id>http://www.tddfellow.com/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through</id>
    <content type="html"><![CDATA[<p>Welcome back to the &ldquo;Getting Stuck While Doing TDD&rdquo; series. Today we are going to see the results of getting stuck while doing TDD and scratch the surface of how to avoid this outcome.</p>

<p>Code examples today will be in Ruby programming language. The technique itself is, of course, language-agnostic.</p>

<h2>TL;DR</h2>

<ul>
<li>It is painful and difficult to force your way through when getting stuck in TDD.</li>
<li>It results in degraded guarantees from TDD (such as test coverage, semantical stability, and confidence).</li>
</ul>


<p>Ways to avoid this outcome:</p>

<ul>
<li>do not write tests that will not fail with the current production code</li>
<li>choose next test to write that will address particular detail about production code that is wrong or not general enough (Triangulation)</li>
</ul>


<p>Finally, do not forget to remove redundant tests if any.</p>

<!--more-->


<p>This is a series of articles:</p>

<ol>
<li><a href="/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example/">Part 1: Example</a></li>
<li>Part 2: Buggy Code and Forcing Our Way Through (reading this)</li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue/">Part 3: Triangulation to the Rescue!</a></li>
</ol>


<h2>Buggy if-riddled code</h2>

<p>Buggy <code>if</code>-riddled code is what we&rsquo;ve got. It is even not so easy to read. While we can refactor it to be more readable that won&rsquo;t change the presence of bugs, though. Let&rsquo;s still do it to understand what happens in this code better:</p>

<pre><code class="ruby">class OrderKindValidator
  def validate(order)
    kinds = order[:kind]

    validate_only_known(kinds)
    validate_has_required(kinds)
    validate_no_conflicting(kinds)
    validate_non_empty(kinds)
  end

  private

  def validate_non_empty(kinds)
    if empty?(kinds)
      fail_with("Order kind can not be empty")
    end
  end

  def validate_no_conflicting(kinds)
    if has_conflicting(kinds)
      fail_with("Order kind can not be 'private' and 'corporate' at the same time")
    end
  end

  def validate_has_required(kinds)
    if has_no_required(kinds)
      fail_with("Order kind should be 'private' or 'corporate'")
    end
  end

  def validate_only_known(kinds)
    if invalid?(kinds)
      fail_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    end
  end

  def empty?(kind)
    kind != ["private"] &amp;&amp; kind != ["corporate"] &amp;&amp;
        kind != %w(private bundle) &amp;&amp;
        kind != %w(corporate bundle)
  end

  def has_conflicting(kind)
    kind == %w(private corporate)
  end

  def has_no_required(kind)
    kind == ["bundle"]
  end

  def invalid?(kind)
    kind == ["invalid"]
  end

  def fail_with(message)
    raise InvalidOrderError.new(message)
  end
end
</code></pre>

<p>Structure of the class, actually, sounds just right, but conditions are not good:</p>

<pre><code class="ruby">def empty?(kind)
  kind != ["private"] &amp;&amp; kind != ["corporate"] &amp;&amp;
      kind != %w(private bundle) &amp;&amp;
      kind != %w(corporate bundle)
end
</code></pre>

<p>Really? It does not do what it says. At all. It basically just solves the problem very specifically to the tests. I can easily come up with a test that will break it:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    .when_order_kind_is ["almost anything"]

# Error: expected InvalidOrderError with
#    "Order kind can be one of: 'private', 'corporate', 'bundle'",
# got #&lt;InvalidOrderError: Order kind can not be empty&gt;

# or other test
it_does_not_fail.when_order_kind_is %w(corporate corporate)
</code></pre>

<pre><code class="ruby">def has_conflicting(kind)
  kind == %w(private corporate)
end
</code></pre>

<p>This at least does what it says. But only for one specific case, instead of general one. One test that I can come up with right away:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be 'private' and 'corporate' at the same time")
    .when_order_kind_is %w(private corporate bundle)

# and another one:
it_fails_with("Order kind can not be 'private' and 'corporate' at the same time")
    .when_order_kind_is %w(corporate private)
</code></pre>

<pre><code class="ruby">def has_no_required(kind)
  kind == ["bundle"]
end
</code></pre>

<p>While this may work for our current requirements, it is really confusing for the reader. Method name says: &ldquo;has no required kind&rdquo; while method body checks if it is only <code>bundle</code>. And it does not work well with that edge case:</p>

<pre><code class="ruby">it_fails_with("Order kind should be 'private' or 'corporate'")
    .when_order_kind_is %w(bundle bundle)
</code></pre>

<p>While this case is quite unlikely, nothing in business rules forbid that and some other part of the system may as well duplicate <code>bundle</code> kind for some reason or it may be a user input mistake.</p>

<pre><code class="ruby">def invalid?(kind)
  kind == ["invalid"]
end
</code></pre>

<p>This method, indeed, checks that <code>kind</code> is <code>invalid</code>. Literally <code>"invalid"</code>. Which would mean, that all kinds except exactly <code>"invalid"</code> are allowed. This is not true according to our business rules. In fact, we have already written the failing test for this some moments ago:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    .when_order_kind_is ["almost anything"]
</code></pre>

<p>Let&rsquo;s comment out these failing tests and try to force-TDD our way through these bugs by uncommenting and fixing them one-by-one following Red-Green-Refactor loop:</p>

<h2>Forcing our way through</h2>

<p>So, let&rsquo;s uncomment our first failing test:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    .when_order_kind_is ["almost anything"]
</code></pre>

<p>We are expecting <code>validate_only_known</code> to fail with its message and that means <code>invalid?(kinds)</code> should return true. To make it return <code>true</code> in this case and preserve its old behavior we will need to remove <code>private</code>, <code>corporate</code> and <code>bundle</code> from <code>kinds</code> and check that it is not empty:</p>

<pre><code class="ruby">def invalid?(kinds)
  (kinds - %w(private corporate bundle)).any?
end
</code></pre>

<p>See how we had to write the whole thing in one go. There is no chance to write it incrementally because there will be a bunch of tests that fail. Wait! While it does not fail for any tests related to invalid kinds, it fails for all tests related to emptiness:</p>

<pre><code>OrderKindValidator
  fails with message "Order kind can not be empty"
    when order kind is [""] (FAILED - 1)
    when order kind is ["", ""] (FAILED - 2)
    when order kind is ["private", ""] (FAILED - 3)
    when order kind is absent (FAILED - 4)
    when order kind is nil (FAILED - 5)
</code></pre>

<p>So we need to change more production code to make this one tiny test pass. It looks like <code>validate_non_empty</code> is a culprit now - it is being called after <code>validate_only_known</code>. It should be the other way around:</p>

<pre><code class="ruby">def validate(order)
  kinds = order[:kind]

  validate_non_empty(kinds)
# ^ we moved this up here ^

  validate_only_known(kinds)
  validate_has_required(kinds)
  validate_no_conflicting(kinds)
end
</code></pre>

<p>Oh! Now a bunch of other tests fails:</p>

<pre><code>OrderKindValidator
  fails with message "Order kind should be 'private' or 'corporate'"
    when order kind is ["bundle"] (FAILED - 1)

  fails with a message "Order kind can not be 'private' and 'corporate' at the same time"
    when order kind is ["private", "corporate"] (FAILED - 4)

  fails with a message "Order kind can be one of: 'private', 'corporate', 'bundle'"
    when order kind is ["almost anything"] (FAILED - 2)
    when order kind is ["invalid"] (FAILED - 3)
</code></pre>

<p>From failure messages it is possible to guess, that the culprit is <code>empty?(kinds)</code> function that fails in too much cases now, such as: <code>["bundle"]</code>, <code>["private", "corporate"]</code>, <code>["almost anything"]</code> and <code>["invalid"]</code>. This is because it was not doing what it said it was:</p>

<pre><code class="ruby">def empty?(kinds)
  kinds != ["private"] &amp;&amp; kinds != ["corporate"] &amp;&amp;
      kinds != %w(private bundle) &amp;&amp;
      kinds != %w(corporate bundle)
end
</code></pre>

<p>And this is why it was hard to change the order of validations. We will have to completely rewrite this function. Let&rsquo;s start small and see which tests fail:</p>

<pre><code class="ruby">def empty?(kinds)
  false
end
</code></pre>

<p>The failures are:</p>

<pre><code>OrderKindValidator
  fails with message "Order kind can not be empty"
    when order kind is ["private", ""] (FAILED - 1)
    when order kind is [nil] (FAILED - 2)
    when order kind is ["", ""] (FAILED - 3)
    when order kind is nil (FAILED - 4)
    when order kind is [""] (FAILED - 5)
    when order kind is absent (FAILED - 6)
    when order kind is [nil, nil] (FAILED - 7)
    when order kind is ["private", nil] (FAILED - 8)
    when order kind is [] (FAILED - 9)
</code></pre>

<p>Good, only tests related directly to this case are failing. So one-by-one we can construct our condition while fixing these test failures:</p>

<ol>
<li><code>kinds.nil?</code></li>
<li><code>|| kinds.empty?</code></li>
<li><code>|| kinds[0].nil?</code>   (turned out to be redundant in the end)</li>
<li><code>|| kinds[0].empty?</code> (turned out to be redundant in the end)</li>
<li><code>|| kinds.any? { |k| k.nil? || k.empty? }</code></li>
</ol>


<p>After refactoring <code>empty?</code> the function now is looking this way:</p>

<pre><code class="ruby">def empty?(kinds)
  absent_or_empty?(kinds) ||
      kinds.any? { |kind| absent_or_empty?(kind) }
end

def absent_or_empty?(value)
  value.nil? || value.empty?
end
</code></pre>

<p>And all tests, finally, pass. It took a lot of effort and re-writing to get this one little test to pass. This is what we call &ldquo;Getting Stuck&rdquo; in TDD. There is always an order of tests that will lead to this result almost for any somewhat complex problem.</p>

<p>The code can be found in GitHub repository in <a href="https://github.com/waterlink/order_kind_validator/pull/2/files">an open pull request here</a>.</p>

<p>Almost guaranteed ways to get stuck in TDD:</p>

<ul>
<li>write tests that do not fail,</li>
<li>do not address weird results of &ldquo;simplest thing that could possibly work&rdquo; to make the test pass and moving on to the next business rule,</li>
<li>make production code a mirror of the tests and too specific, not general.</li>
</ul>


<p>And to not get stuck is to do the opposite:</p>

<ul>
<li>do not write the test that will not fail (wait until later, when it will fail), and</li>
<li>always first write the test that will point out next deficiency in the current production code (in TDD this is called Triangulation), and</li>
<li>while making some failing test pass, make sure that the change in production code covers not only this one specific test, rather, a whole class of tests (Golden Rule of TDD: As tests get more specific, production code gets more generic).</li>
</ul>


<h2>Bottom Line</h2>

<p>Today we have seen how bad the results of getting stuck while doing TDD can be. In the next article of these series, we will explore Golden Rule of TDD and the technique called Triangulation, that allows us to incrementally test-drive code in a way, that it will always be conforming to the Golden Rule of TDD and therefore will never get us stuck. Stay tuned!</p>

<p>This is a series of articles:</p>

<ol>
<li><a href="/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example/">Part 1: Example</a></li>
<li>Part 2: Buggy Code and Forcing Our Way Through (reading this)</li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue/">Part 3: Triangulation to the Rescue!</a></li>
</ol>


<p>You would not want to miss next articles on this tech blog, we still have a lot to talk about:</p>

<ul>
<li>Triangulation technique in Test-Driven Development - overlooking this technique might cause one fail at doing TDD (these series),</li>
<li>Continuous Integration and Continuous Delivery - importance of not impeding others,</li>
<li>Open-Closed Principle - changing behavior by adding new code,</li>
<li>Mutational Testing, &ldquo;Build Your Own Testing Framework&rdquo; series, Test-Driven Development screencasts and so much more!</li>
</ul>


<h2>Thanks!</h2>

<p>Thank you for reading, my dear reader. If you liked it, please share this article on social networks and follow me on twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>

<p>If you have any questions or feedback for me, don&rsquo;t hesitate to reach me out on Twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Getting Stuck While Doing TDD. Part 1: Example]]></title>
    <link href="http://www.tddfellow.com/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example/"/>
    <updated>2016-08-30T15:27:30+02:00</updated>
    <id>http://www.tddfellow.com/blog/2016/08/30/getting-stuck-while-doing-tdd-part-1-example</id>
    <content type="html"><![CDATA[<p>Following 3 rules of TDD sounds really simple at first. In practice, there is a moment when one has to implement the whole algorithm at once to make currently failing test pass. This is called &ldquo;getting stuck&rdquo; in TDD. In this article, we will explore how exactly this happens and how to prevent that.</p>

<p>Code examples today will be in Ruby programming language. The technique itself is, of course, language-agnostic.</p>

<h2>TL;DR</h2>

<p>&ldquo;Getting stuck&rdquo; happens for a couple of reasons:</p>

<ul>
<li>wrong order of tests</li>
<li>production code is not getting more general with each test</li>
</ul>


<!--more-->


<p>This is a series of articles:</p>

<ol>
<li>Part 1: Example (reading this)</li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through/">Part 2: Buggy Code and Forcing Our Way Through</a></li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue/">Part 3: Triangulation to the Rescue!</a></li>
</ol>


<h2>&ldquo;Getting Stuck&rdquo; in TDD</h2>

<p>Usually &ldquo;Getting Stuck&rdquo; follows this pattern:</p>

<ul>
<li>write some test and implement it via &ldquo;simplest thing that might possibly work&rdquo;,</li>
<li>write another test and implement it again in a non-general manner,</li>
<li>write some more tests in that fashion, while never addressing the fact that production code now looks completely wrong from what it should probably be looking like,</li>
<li>write a new test, that forces us to completely rewrite production code in a complete algorithm just to make it pass.</li>
</ul>


<p>This last step usually takes minutes to hours depending on the complexity of the problem at hand. Additionally, the first few tests are basically wasted time since they did not produce any bits of knowledge in the production code that persisted in production code in the end. Even worse, chances are that the algorithm that we have just written is not fully covered by current tests, since we have written it in one go just to make current failing test pass - this is no longer correct TDD and can not guarantee high test coverage, and, therefore, can not guarantee high confidence anymore.</p>

<p>Let&rsquo;s go through a small example on how one can get stuck in TDD:</p>

<h2>Order Kind Validation - Getting Stuck</h2>

<p>Let&rsquo;s define the problem at hand first. We have some sort of order request as an input to our system and we need to validate that its kind is correct:</p>

<ul>
<li>valid order kinds: <code>private</code>, <code>corporate</code>, <code>bundle</code>,</li>
<li>order kinds can be combined,</li>
<li><code>private</code> and <code>corporate</code> order kinds can not be combined, otherwise <code>InvalidOrderError</code> with message <code>Order kind can not be 'private' and 'corporate' at the same time</code>,</li>
<li>either <code>private</code> or <code>corporate</code> should be always present, otherwise <code>InvalidOrderError</code> with message <code>Order kind should be 'private' or 'corporate'</code>,</li>
<li>if order kind is not in the above list, then we need to raise <code>InvalidOrderError</code> with message <code>Order kind can be one of: 'private', 'corporate', 'bundle'</code>,</li>
<li>if order kind is not present or an empty string, then we need to raise <code>InvalidOrderError</code> with message <code>Order kind can not be empty</code>.</li>
</ul>


<p>This is a fairly simple problem and it is easy to get stuck while doing TDD here. So let&rsquo;s write our first test: &ldquo;When order has no order_kind, then we should get InvalidOrderError with message &lsquo;Order kind can not be empty&rsquo;&rdquo;:</p>

<pre><code class="ruby">RSpec.describe OrderKindValidator do
  it "fails with a message about order kind being empty when it is absent" do
    validator = OrderKindValidator.new

    expect { validator.validate({ items: 42 }) }
        .to raise_error(InvalidOrderError, "Order kind can not be empty")
  end
end
</code></pre>

<p>And the simplest implementation possible:</p>

<pre><code class="ruby">class OrderKindValidator
  def validate(order)
    raise InvalidOrderError.new("Order kind can not be empty")
  end
end

class InvalidOrderError &lt; StandardError
end
</code></pre>

<p>Next test is our next simplest edge case - when kind&rsquo;s value is <code>nil</code>:</p>

<pre><code class="ruby">it "fails with a message about order kind being empty when it is nil" do
  validator = OrderKindValidator.new

  expect { validator.validate({items: 42, kind: nil }) }
      .to raise_error(InvalidOrderError, "Order kind can not be empty")
end
</code></pre>

<p>It does not fail at all, so we don&rsquo;t have any reason to change the production code. We can already spot a little duplication - <code>validator</code> variable. Let&rsquo;s extract it as a named subject of the test suite:</p>

<pre><code class="ruby">subject(:validator) { OrderKindValidator.new }
</code></pre>

<p>And <code>OrderKindValidator</code> can be replaced with <code>described_class</code> (RSpec feature), so that we will not have to change too much in case we wanted to change name of the class:</p>

<pre><code class="ruby">subject(:validator) { described_class.new }
</code></pre>

<p>Next simplest edge case - when kind is an empty array:</p>

<pre><code class="ruby">it "fails with a message about order kind being empty when it has zero elements" do
  expect { validator.validate({items: 42, kind: [] }) }
      .to raise_error(InvalidOrderError, "Order kind can not be empty")
end
</code></pre>

<p>I believe I am spotting annoying pattern now:</p>

<pre><code class="ruby">it "fails with message MESSAGE when it is KIND_CASE" do
  expect { validator.validate({items: 42, kind: KIND_VALUE}) }
    .to raise_error(InvalidOrderError, MESSAGE)
end
</code></pre>

<p>It would be really nice to write it in this fashion:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be empty").when_order_kind_is_absent
it_fails_with("Order kind can not be empty").when_order_kind_is nil
it_fails_with("Order kind can not be empty").when_order_kind_is []
</code></pre>

<p>And as another duplication piles up:</p>

<pre><code class="ruby">it_fails_with_order_kind_not_empty = it_fails_with("Order kind can not be empty")

it_fails_with_order_kind_not_empty.when_order_kind_is_absent
it_fails_with_order_kind_not_empty.when_order_kind_is nil
it_fails_with_order_kind_not_empty.when_order_kind_is []
</code></pre>

<p>Now the next tests look very easy and simple:</p>

<pre><code class="ruby">it_fails_with_order_kind_not_empty.when_order_kind_is [nil]
it_fails_with_order_kind_not_empty.when_order_kind_is [""]
it_fails_with_order_kind_not_empty.when_order_kind_is [nil, nil]
it_fails_with_order_kind_not_empty.when_order_kind_is ["", ""]
it_fails_with_order_kind_not_empty.when_order_kind_is ["private", ""]
it_fails_with_order_kind_not_empty.when_order_kind_is ["private", nil]
</code></pre>

<p>And they all pass right from the go. The implementation for the <code>it_fails_with</code> is looking like this:</p>

<pre><code class="ruby">RSpec.describe OrderKindValidator do
  class ItFailsWith
    def initialize(spec, expected_message)
      @spec = spec
      @expected_message = expected_message
    end

    def when_order_kind_is_absent
      expect_failure("absent", {items: 42})
    end

    def when_order_kind_is(value)
      expect_failure(value.inspect, {items: 42, kind: value})
    end

    private

    def expect_failure(feature, order, expected_message = @expected_message)
      @spec.it("fails with message #{expected_message.inspect} when order kind is #{feature}") do
        expect { validator.validate(order) }
            .to raise_error(InvalidOrderError, expected_message)
      end
    end
  end

  def self.it_fails_with(message)
    ItFailsWith.new(self, message)
  end
end
</code></pre>

<p>So, let&rsquo;s write our next edge case - when order kind is invalid:</p>

<pre><code class="ruby">it_fails_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    .when_order_kind_is ["invalid"]
</code></pre>

<p>Pretty neat! And oh, it fails:</p>

<pre><code>expected InvalidOrderError with
  "Order kind can be one of: 'private', 'corporate', 'bundle'",
got #&lt;InvalidOrderError: Order kind can not be empty&gt;
</code></pre>

<p>And the fix:</p>

<pre><code class="ruby">def validate(order)
  if order[:kind] == ["invalid"]
    raise InvalidOrderError.new(
        "Order kind can be one of: 'private', 'corporate', 'bundle'"
    )
  end

  raise InvalidOrderError.new("Order kind can not be empty")
end
</code></pre>

<p>Let&rsquo;s write our next test - when order kind is <code>private</code>:</p>

<pre><code class="ruby">it_does_not_fail.when_order_kind_is ["private"]
</code></pre>

<p>This fails as expected with <code>expected no Exception, got #&lt;InvalidOrderError: Order kind can not be empty&gt;</code>. And to make it pass we need to wrap second <code>raise</code> statement in the <code>if</code> condition:</p>

<pre><code class="ruby">if order[:kind] != ["private"]
  raise InvalidOrderError.new("Order kind can not be empty")
end
</code></pre>

<p>The implementation for <code>it_does_not_fail</code> looks like that:</p>

<pre><code class="ruby">class ItDoesNotFail
  def initialize(spec)
    @spec = spec
  end

  def when_order_kind_is(value)
    @spec.it("does not fail when order kind is #{value.inspect}") do
      expect { validator.validate({items: 42, kind: value}) }
        .not_to raise_error
    end
  end
end

def self.it_does_not_fail
  ItDoesNotFail.new(self)
end
</code></pre>

<p>Let&rsquo;s write our next test:</p>

<pre><code class="ruby">it_does_not_fail.when_order_kind_is ["corporate"]
</code></pre>

<p>And it fails with the expected error: <code>expected no Exception, got #&lt;InvalidOrderError: Order kind can not be empty&gt;</code>. The fix is to amend our <code>if</code> condition with that case:</p>

<pre><code class="ruby">if order[:kind] != ["private"] &amp;&amp; order[:kind] != ["corporate"]
                                # ^  we have added this case  ^
  raise InvalidOrderError.new("Order kind can not be empty")
end
</code></pre>

<p>And the tests pass. Our next business rule is that one of <code>private</code> and <code>corporate</code> should be always present:</p>

<pre><code class="ruby">it_fails_with("Order kind should be 'private' or 'corporate'")
    .when_order_kind_is ["bundle"]
</code></pre>

<p>As expected the test fails:</p>

<pre><code>expected InvalidOrderError with
  "Order kind should be 'private' or 'corporate'",
got #&lt;InvalidOrderError: Order kind can not be empty&gt;
</code></pre>

<p>And to fix it we just need to sprinkle another <code>if</code> statement in the middle of the function:</p>

<pre><code class="ruby">if order[:kind] == ["bundle"]
  raise InvalidOrderError.new("Order kind should be 'private' or 'corporate'")
end
</code></pre>

<p>As expected, the test passes. Now we should test the next business rule - order can not be of <code>private</code> and <code>corporate</code> kind at the same time:</p>

<pre><code class="ruby">it_fails_with("Order kind can not be 'private' and 'corporate' at the same time")
    .when_order_kind_is %w(private corporate)
</code></pre>

<p>This, as expected, fails with error message:</p>

<pre><code>expected InvalidOrderError with
  "Order kind can not be 'private' and 'corporate' at the same time",
got #&lt;InvalidOrderError: Order kind can not be empty&gt;
</code></pre>

<p>And easiest way to fix that is to add another <code>if</code> statement:</p>

<pre><code class="ruby">if order[:kind] == %w(private corporate)
  raise InvalidOrderError.new(
      "Order kind can not be 'private' and 'corporate' at the same time"
  )
end
</code></pre>

<p>And it passes. Let&rsquo;s test that we can combine <code>private</code> or <code>corporate</code> with <code>bundle</code> order kinds:</p>

<pre><code class="ruby">it_does_not_fail.when_order_kind_is %w(private bundle)
</code></pre>

<p>And it fails with error: <code>expected no Exception, got #&lt;InvalidOrderError: Order kind can not be empty&gt;</code>. To fix this we will have to amend our last <code>if</code> condition in the function even more:</p>

<pre><code class="ruby">if order[:kind] != ["private"] &amp;&amp; order[:kind] != ["corporate"] &amp;&amp;
    order[:kind] != %w(private bundle)
  # ^    this is our new condition    ^
  raise InvalidOrderError.new("Order kind can not be empty")
end
</code></pre>

<p>And the test passes. Let&rsquo;s refactor the code a bit:</p>

<ul>
<li>First, we should extract <code>order[:kind]</code> duplication to a local variable <code>kind</code></li>
<li>Extract common parts of <code>raise</code> statement to the private method</li>
</ul>


<p>After this, <code>OrderKindValidator</code> will look a bit cleaner:</p>

<pre><code class="ruby">class OrderKindValidator
  def validate(order)
    kind = order[:kind]

    if kind == ["invalid"]
      fail_with("Order kind can be one of: 'private', 'corporate', 'bundle'")
    end

    if kind == ["bundle"]
      fail_with("Order kind should be 'private' or 'corporate'")
    end

    if kind == %w(private corporate)
      fail_with("Order kind can not be 'private' and 'corporate' at the same time")
    end

    if kind != ["private"] &amp;&amp; kind != ["corporate"] &amp;&amp;
        kind != %w(private bundle)
      fail_with("Order kind can not be empty")
    end
  end

  private

  def fail_with(message)
    raise InvalidOrderError.new(message)
  end
end
</code></pre>

<p>Let&rsquo;s write our next test for the same business rule (now a corporate bundle):</p>

<pre><code class="ruby">it_does_not_fail.when_order_kind_is %w(corporate bundle)
</code></pre>

<p>And it fails with error: <code>expected no Exception, got #&lt;InvalidOrderError: Order kind can not be empty&gt;</code>. To fix this we need to add <code>&amp;&amp; kind != %w(corporate bundle)</code> to our last <code>if</code> condition again.</p>

<p>The code can be found in GitHub repository in <a href="https://github.com/waterlink/order_kind_validator/pull/1/files">an open pull request here</a>.</p>

<p>Now it seems that we have implemented all the business rules (we have all tests for them). Or did we?</p>

<h2>Bottom Line</h2>

<p>Buggy <code>if</code>-riddled code is what we&rsquo;ve got. We will see why in the next part of &ldquo;Getting Stuck While Doing TDD&rdquo; series. Stay tuned!</p>

<p>This is a series of articles:</p>

<ol>
<li>Part 1: Example (reading this)</li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-2-buggy-code-and-forcing-our-way-through/">Part 2: Buggy Code and Forcing Our Way Through</a></li>
<li><a href="/blog/2016/08/31/getting-stuck-while-doing-tdd-part-3-triangulation-to-the-rescue/">Part 3: Triangulation to the Rescue!</a></li>
</ol>


<p>Today we have implemented our not-so-complex problem at hand while following 3 rules of TDD. The result was not of the best quality and we will take a look why in further articles of these series. You would not want to miss next articles on this tech blog, we still have a lot to talk about:</p>

<ul>
<li>Triangulation technique in Test-Driven Development - overlooking this technique might cause one fail at doing TDD (these series),</li>
<li>Continuous Integration and Continuous Delivery - importance of not impeding others,</li>
<li>Open-Closed Principle - changing behavior by adding new code,</li>
<li>Mutational Testing, &ldquo;Build Your Own Testing Framework&rdquo; series, Test-Driven Development screencasts and so much more!</li>
</ul>


<h2>Thanks!</h2>

<p>Thank you for reading, my dear reader. If you liked it, please share this article on social networks and follow me on twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>

<p>If you have any questions or feedback for me, don&rsquo;t hesitate to reach me out on Twitter: <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[TDD #5: English Numbers Kata]]></title>
    <link href="http://www.tddfellow.com/blog/2016/06/19/tdd-number-5-english-numbers-kata/"/>
    <updated>2016-06-19T18:41:39+02:00</updated>
    <id>http://www.tddfellow.com/blog/2016/06/19/tdd-number-5-english-numbers-kata</id>
    <content type="html"><![CDATA[<iframe src="https://player.vimeo.com/video/171307899?color=c9ff23" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>


<p><a href="https://vimeo.com/171307899">Test-Driven Development Screencast #5: English Numbers Kata</a></p>

<p><em>(Recommended to watch full-screen and HD: 720p or more)</em></p>

<p>List of all TDD Screencasts can be <a href="/blog/categories/tdd-screencasts/">found here</a>.</p>

<p>This screencast was born from my previous blog post: <a href="/blog/2016/05/27/iterative-divide-and-conquer-or-how-to-solve-problems/">Iterative Divide &amp; Conquer or How to solve problems</a>.</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Iterative Divide &amp; Conquer or How to Solve Problems]]></title>
    <link href="http://www.tddfellow.com/blog/2016/05/27/iterative-divide-and-conquer-or-how-to-solve-problems/"/>
    <updated>2016-05-27T07:48:18+02:00</updated>
    <id>http://www.tddfellow.com/blog/2016/05/27/iterative-divide-and-conquer-or-how-to-solve-problems</id>
    <content type="html"><![CDATA[<p><em>Let&rsquo;s imagine a beginner programmer, who have learned a programming language basics, can write programs and can read someone else&rsquo;s programs. Now, for any somewhat non-trivial problem, they have trouble coming up with a solution. And if they read one of the possible solutions, they will understand it and conclude: &ldquo;I understand how this program works, but I don&rsquo;t know how to get there.&rdquo;. If that sounds like you, my dear reader, or someone you would like to coach or teach, then come and learn Iterative Divide &amp; Conquer problem-solving technique.</em></p>

<h2>English Numbers Kata</h2>

<p>Given an integer number in the range of <code>-999 999 999</code> to <code>999 999 999</code>, write a program, that will output that number in English words.</p>

<p>Example:</p>

<p>Given number <code>37545</code>, the program outputs <code>thirty-seven thousands five hundred forty-five</code>.</p>

<h3>I can solve that!</h3>

<p>If you are confident, that you are able to solve that problem, my congratulations, you have problem-solving skill at a necessary level!</p>

<p>If you still feel, that you can solve this Kata easily, although there are more complex problems that give you troubles, then, probably, your problem-solving strategy is not scalable. The technique described in this article is scalable.</p>

<h3>Let&rsquo;s dive in</h3>

<p><em>NOTE: this article uses pseudo-code, that doesn&rsquo;t belong to any programming language, so it makes sense for you, my reader, to implement this step-by-step in the programming language you know.</em></p>

<p>OK. Let&rsquo;s imagine, that you don&rsquo;t know how to solve the whole English Numbers Kata and you don&rsquo;t even know where to start.</p>

<p>Now, let&rsquo;s try to solve much simpler problem:</p>

<p>Given an integer number in the range of <code>0</code> to <code>9</code>, write a program that will output that number in English words.</p>

<p>Can you solve that? I am pretty sure you can. And easily at that.</p>

<p>Let&rsquo;s write down some of our possible inputs and corresponding outputs:</p>

<pre><code class="ruby">print english_number(0)   # zero
print english_number(1)   # one
print english_number(7)   # seven
print english_number(9)   # nine
</code></pre>

<p>If we run that program, we will get an error, that <code>english_number</code> function is not defined yet. Let&rsquo;s define it:</p>

<pre><code class="javascript">function english_number(number) {
  return ""
}
</code></pre>

<p>Now if we run our program, we will get four empty lines on the screen as expected. Easiest implementation of <code>english_number</code> function would probably look like that:</p>

<pre><code class="javascript">if (number == 0) {
  return "zero"
} else if (number == 1) {
  return "one"
} else if (number == 2) {
  return "two"
} else if (number == 3) {
  return "three"
} else if (number == 4) {
  return "four"
} else if (number == 5) {
  return "five"
} else if (number == 6) {
  return "six"
} else if (number == 7) {
  return "seven"
} else if (number == 8) {
  return "eight"
} else if (number == 9) {
  return "nine"
}
</code></pre>

<p>If we run our program, then we will get our expected output:</p>

<pre><code>zero
one
seven
nine
</code></pre>

<p>If you already know arrays and access array by index, <code>english_number</code> can be simplified greatly:</p>

<pre><code class="javascript">NUMBERS = ["zero", "one", "two", "three", "four",
           "five", "six", "seven", "eight", "nine"]

function english_number(number) {
  return NUMBERS[number]
}
</code></pre>

<p>After making this change, let&rsquo;s run the program, we should see the same output:</p>

<pre><code>zero
one
seven
nine
</code></pre>

<p>OK. Seems like we have solved our current problem at hand. What about the initial problem? How do we get there?</p>

<h3>Increase size of the problem slightly</h3>

<p>Or as you would say in real-world programming: Add a new requirement.</p>

<p>Our initial problem has only two axes, where we can add requirements to our current solution to move it towards final solution:</p>

<ul>
<li>increase the supported range</li>
<li>allow negative integers</li>
</ul>


<p>Let&rsquo;s go with latter, it seems easier. First we write down our possible inputs and outputs:</p>

<pre><code class="ruby">print english_integer(0)     # zero
print english_integer(4)     # four
print english_integer(-3)    # minus three
print english_integer(9)     # nine
print english_integer(-9)    # minus nine
</code></pre>

<p>Now, implement <code>english_integer</code> as a simple call to <code>english_number</code> (that will make half of our inputs produce correct output):</p>

<pre><code class="javascript">function english_integer(number) {
  return english_number(number)
}
</code></pre>

<p>Depending on what your programming language this can:</p>

<ul>
<li>output partly incorrect data (for negative values)</li>
<li>fail at run time</li>
<li>fail at compile time</li>
</ul>


<p>We can fix that by handling the case of negative numbers:</p>

<pre><code class="javascript">if (number &lt; 0) {
  return "minus " + english_integer(-number)
} else {
  return english_number(number)
}
</code></pre>

<p>That might be confusing at first. Especially, part, where we call <code>english_integer</code> from the body of the same function. Let&rsquo;s draw a diagram on how that function works:</p>

<p><img src="https://camo.githubusercontent.com/134fbbce495dc2d9bb3f137077cdde57dc28668e/687474703a2f2f672e67726176697a6f2e636f6d2f673f2530412532302532306469677261706825323047253230253742253041253230253230253230253230666f7263656c6162656c733d747275653b253041253230253230253230253230253232656e676c6973685f696e7465676572286e756d6265722925323225323025354273686170653d626f782535443b2530412532302532302532302532302532326966253230286e756d626572253230253343253230302925323225323025354273686170653d6469616d6f6e642535443b25304125323025323025323025323025323263616c6c253230656e676c6973685f696e7465676572282d6e756d626572292532323b25304125323025323025323025323025323263616c6c253230656e676c6973685f6e756d626572286e756d626572292532323b25304125323025323025323025323025323270726570656e64253230726573756c7425323077697468253230276d696e7573253230272532323b253041253230253230253230253230253232616e6425323072657475726e25323069742532323b2530412532302532302532302532302532327468656e25323072657475726e253230726573756c742532306f662532307468697325323063616c6c2532323b253041253230253230253230253230253232656e676c6973685f696e7465676572286e756d626572292532322532302d2533452532302532326966253230286e756d62657225323025334325323030292532323b2530412532302532302532302532302532326966253230286e756d62657225323025334325323030292532323a652532302d25334525323025323263616c6c253230656e676c6973685f696e7465676572282d6e756d626572292532322532302535426c6162656c3d2532325945532532322535443b2530412532302532302532302532302532326966253230286e756d62657225323025334325323030292532323a772532302d25334525323025323263616c6c253230656e676c6973685f6e756d626572286e756d626572292532322532302535426c6162656c3d2532324e4f2535436e696e76617269616e743a2535436e6e756d6265722532302533453d253230302532322535443b25304125323025323025323025323025323263616c6c253230656e676c6973685f696e7465676572282d6e756d626572292532323a6e652532302d253345253230253232656e676c6973685f696e7465676572286e756d626572292532323a6e652532302535426c6162656c3d253232696e76617269616e743a2535436e6e756d6265722532302533453d253230302532322535443b25304125323025323025323025323025323263616c6c253230656e676c6973685f696e7465676572282d6e756d626572292532322532302d25334525323025323270726570656e64253230726573756c7425323077697468253230276d696e7573253230272532322532302d253345253230253232616e6425323072657475726e25323069742532323b25304125323025323025323025323025323263616c6c253230656e676c6973685f6e756d626572286e756d626572292532322532302d2533452532302532327468656e25323072657475726e253230726573756c742532306f662532307468697325323063616c6c2532323b253041253230253230253744" alt="Diagram for english_integer after adding negative integers" /></p>

<p>If we were to unwind this diagram into possible paths, we would end up with two possible cases:</p>

<ol>
<li>When <code>number &lt; 0</code>:

<ul>
<li><code>english_integer(number)</code></li>
<li><code>if (number &lt; 0)</code> - YES</li>
<li><code>english_integer(-number)</code></li>
<li><code>if (number &lt; 0)</code> - NO</li>
<li><code>english_number(number)</code></li>
<li>prepend result of last call with <code>minus</code></li>
<li>and return it</li>
</ul>
</li>
<li>When <code>number &gt;= 0</code>:

<ul>
<li><code>english_integer(number)</code></li>
<li><code>if (number &lt; 0)</code> - NO</li>
<li><code>english_number(number)</code></li>
<li>return result of last call</li>
</ul>
</li>
</ol>


<p>Running this program results in expected output:</p>

<pre><code>zero
four
minus three
nine
minus nine
</code></pre>

<p>Implementation of <code>english_integer(number)</code> function can be simplified by eliminating <code>else</code> clause and treating <code>number &lt; 0</code> as an edge case and using &ldquo;guard clause&rdquo; to handle it:</p>

<pre><code class="javascript">function english_integer(number) {
  if (number &lt; 0) return "minus " + english_integer(-number)

  return english_number(number)
}
</code></pre>

<p>If we run our program, the output should be the same as before.</p>

<h3>Add more requirements!</h3>

<p>Now, that we are done with handling a negative case, we have only one requirement axis left: range of integers. Currently, we support integers from <code>-9</code> to <code>9</code>. Now let&rsquo;s extend support for integers from <code>10</code> to <code>19</code>. This problem should be as trivial as the problem for the range of <code>0...9</code>.</p>

<p>Our inputs with corresponding outputs:</p>

<pre><code class="ruby">print english_teen_number(10)    # ten
print english_teen_number(11)    # eleven
print english_teen_number(13)    # thirteen
print english_teen_number(18)    # eighteen
print english_teen_number(19)    # nineteen
</code></pre>

<p>And the implementation to make the output of the program correct (very similar to <code>english_number</code> function):</p>

<pre><code class="javascript">TEEN_NUMBERS = ["ten", "eleven", "twelve", "thirteen", "fourteen",
                "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]

function english_teen_number(number) {
  // "number - 10" comes from the fact, that range 10..19
  // maps to a range of 0..9 of our array, so we need to
  // shift 10..19 by -10 to get 0..9
  return TEEN_NUMBERS[number - 10]
}
</code></pre>

<p>Now we want to glue our current solution with <code>english_teen_number</code> to add support for range <code>10..19</code>. This sounds like another <code>if .. else</code> case handling:</p>

<ul>
<li>when <code>number &lt; 10</code>, use <code>english_number</code></li>
<li>when <code>number &gt;= 10</code>, use <code>english_teen_number</code></li>
</ul>


<p>Let&rsquo;s change our input/output pairs for <code>english_integer</code> function:</p>

<pre><code class="ruby">print english_integer(0)     # zero
print english_integer(4)     # four
print english_integer(-3)    # minus three
print english_integer(9)     # nine
print english_integer(-9)    # minus nine
print english_integer(10)    # ten
print english_integer(15)    # fifteen
print english_integer(19)    # nineteen
</code></pre>

<p>That should fail in some way (compile error, runtime error or incorrect output). Now it is time to implement missing functionality for last 3 examples in our <code>english_integer</code> function. Replace the last call to <code>english_number</code> with:</p>

<pre><code class="javascript">if (number &lt; 10) {
  return english_number(number)
} else {
  return english_teen_number(number)
}
</code></pre>

<p>If we run the program, we should see correct output:</p>

<pre><code>zero
four
minus three
nine
minus nine
ten
fifteen
nineteen
</code></pre>

<p>What about negative numbers in the range of <code>-19...-10</code>? Let&rsquo;s add input/output examples and see what happens if we run the program:</p>

<pre><code class="ruby">print english_integer(-12)    # minus twelve
print english_integer(-16)    # minus sixteen
print english_integer(-19)    # minus nineteen
</code></pre>

<p>And the output if we run the program:</p>

<pre><code>minus twelve
minus sixteen
minus nineteen
</code></pre>

<p>Yes, it works already thanks to the guard statement that we have at the top of <code>english_integer</code> function. And the whole function body:</p>

<pre><code class="javascript">function english_integer(number) {
  if (number &lt; 0) return "minus " + english_integer(-number)

  if (number &lt; 10) {
    return english_number(number)
  } else {
    return english_teen_number(number)
  }
}
</code></pre>

<h3>Going further!</h3>

<p>Next smallest requirement seems to be an addition of the range <code>20...99</code>. Let&rsquo;s write down our example inputs and outputs:</p>

<pre><code class="ruby">print english_integer_in_tens(20)    # twenty
print english_integer_in_tens(27)    # twenty-seven
print english_integer_in_tens(42)    # forty-two
print english_integer_in_tens(70)    # seventy
print english_integer_in_tens(99)    # ninety-nine
</code></pre>

<p>So how do we solve this problem? Can we follow the same pattern as before, for ranges <code>0...9</code> and <code>10...19</code>?</p>

<p>We certainly do. We create a constant <code>INTEGERS_IN_TENS = [...]</code>, where <code>[...]</code> will contain 79 (mostly two-word) strings. It seems like an excess effort to me. So can we do better?</p>

<p>Yes! We can apply the same problem-solving technique here. What is the smallest problem, that we can solve here easily and independently from other problems?</p>

<p>What about solving the problem only for numbers <code>20</code>, <code>30</code>, <code>40</code>, &hellip;, <code>90</code>? Sounds simple enough! Let&rsquo;s write our example input/outputs:</p>

<pre><code class="ruby">print english_ten(20)    # twenty
print english_ten(30)    # thirty
print english_ten(60)    # sixty
print english_ten(90)    # ninety
</code></pre>

<p>This is no longer different from ranges <code>0...9</code> and <code>10...19</code>. The only detail is that we need to find a way to convert range <code>20...90</code> to <code>0...7</code> to be able to access the array by that index. This can be done in 2 steps:</p>

<ol>
<li>obtain the first digit of the number: <code>number / 10</code>, which results in the range <code>2...9</code>,</li>
<li>and shift resulting digit by <code>-2</code>: <code>number / 10 - 2</code>, which results in the range <code>0...7</code>,</li>
</ol>


<p>exactly, what we expect. Now, we can implement <code>english_ten</code> similarly to <code>english_number</code> and <code>english_teen_number</code>:</p>

<pre><code class="javascript">TENS = ["twenty", "thirty", "forty", "fifty",
        "sixty", "seventy", "eighty", "ninety"]

function english_ten(number) {
  return TENS[number / 10 - 2]
}
</code></pre>

<p>Now it is time to return to the original requirement: support range <code>20...99</code>. Looking at our example input/outputs for a function <code>english_integer_in_tens</code>, we can conclude, that we have 2 different cases:</p>

<ul>
<li>When second digit is 0 (<code>number % 10 == 0</code>):

<ul>
<li>we output only <code>twenty</code>, <code>thirty</code>, &hellip;, <code>ninety</code>, depending on the first digit of the <code>number</code>;</li>
<li>by the way, this is exactly, what <code>english_ten</code> function is doing. Great!</li>
</ul>
</li>
<li>When the second digit is not 0:

<ul>
<li>we output <code>twenty</code>, <code>thirty</code>, &hellip;, <code>ninety</code>, depending on the first digit of the <code>number</code>;</li>
<li>and we output a hyphen character: <code>-</code>;</li>
<li>and we output <code>one</code>, <code>two</code>, &hellip;, <code>nine</code>, depending on the second digit;</li>
<li>by the way, latter is exactly, what <code>english_number</code> function is doing. Great!</li>
</ul>
</li>
</ul>


<p>So, let&rsquo;s implement that in <code>english_integer_in_tens</code>:</p>

<pre><code class="javascript">function english_integer_in_tens(number) {
  second_digit = number % 10

  if (second_digit == 0) {
    return english_ten(number)
  } else {
    return english_ten(number) + " " + english_number(second_digit)
  }
}
</code></pre>

<p>Running the program will produce the expected output:</p>

<pre><code>twenty
twenty-seven
forty-two
seventy
ninety-nine
</code></pre>

<p>Now we should glue the solution for range <code>20...99</code> with our main solution, that currently supports only <code>-19...19</code>. As always, start with example input/outputs:</p>

<pre><code class="ruby">print english_integer(60)   # sixty
print english_integer(43)   # forty-three
print english_integer(-97)  # minus ninety-seven
</code></pre>

<p>This results in incorrect output or failure. How can we merge two solutions together now? Let&rsquo;s remember our current main solution&rsquo;s different cases:</p>

<ul>
<li>Guard <code>number &lt; 0</code>, that prepends &ldquo;minus &rdquo; and makes number non-negative.</li>
<li>When <code>number &lt; 10</code>, use <code>english_number</code>.</li>
<li>Otherwise, use <code>english_teen_number</code>.</li>
</ul>


<p>Seems, like first two cases should not be touched and we are interested in the last one. We should split it in two:</p>

<ul>
<li>Otherwise:

<ul>
<li>When <code>number &lt; 20</code>, use <code>english_teen_number</code>.</li>
<li>Otherwise, use <code>english_integer_in_tens</code>.</li>
</ul>
</li>
</ul>


<p>I believe, we are done and can implement merged version:</p>

<pre><code class="javascript">function english_integer(number) {
  if (number &lt; 0) return "minus " + english_integer(-number)

  if (number &lt; 10) {
    return english_number(number)
  } else if (number &lt; 20) {
    return english_teen_number(number)
  } else {
    return english_integer_in_tens(number)
  }
}
</code></pre>

<p>Running the program confirms that our new solution now supports integers in the range <code>-99...99</code>.</p>

<h3>Final solution</h3>

<p>I&rsquo;m leaving the final solution as an exercise for you, my dear reader. There is nothing more to this technique. Careful application of this technique and careful choice of smallest baby-steps as new requirements to your current solution will get you there - to the final solution, that supports the range of <code>-999 999 999...999 999 999</code>.</p>

<p>If you have any troubles, don&rsquo;t hesitate to share your questions, ideas and code with me. I will try my best to help you, my dear reader. I am reachable via Twitter by handle <a href="https://twitter.com/waterlink000">@waterlink000</a>.</p>

<h2>Challenge</h2>

<p>Extend solution to support floating-point numbers to a precision level of 6 digits after the dot.</p>

<h2>Thank you for reading!</h2>

<p>Final note: did you notice, how tedious it is to check, that output of all these <code>print</code>-s is correct, each time you run the program? This can and should be automated! Stay tuned, I am going to publish an article on how to easily automate these checks really soon!</p>

<p>Next issue is out: <a href="/blog/2016/06/05/automating-manual-checks-or-how-to-save-time-and-get-rapid-feedback/">Automating Manual Checks or How to Save Time and Get Rapid Feedback</a>!</p>
]]></content>
  </entry>
  
</feed>
